run:
  tests: true
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - copyloopvar
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  gofumpt:
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  nolintlint:
    allow-unused: true
    require-explanation: false
    require-specific: false
