version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: true
  exclusions:
    paths:
      - '.*.pb.go'
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
