run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gofumpt:
    extra-rules: true

  nolintlint:
    allow-unused: true
    allow-leading-space: true
    require-explanation: false
    require-specific: false

