// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: neutron/harpoon/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HookType int32

const (
	HookType_AfterValidatorCreated          HookType = 0
	HookType_BeforeValidatorModified        HookType = 1
	HookType_AfterValidatorRemoved          HookType = 2
	HookType_AfterValidatorBonded           HookType = 3
	HookType_AfterValidatorBeginUnbonding   HookType = 4
	HookType_BeforeDelegationCreated        HookType = 5
	HookType_BeforeDelegationSharesModified HookType = 6
	HookType_BeforeDelegationRemoved        HookType = 7
	HookType_AfterDelegationModified        HookType = 8
	HookType_BeforeValidatorSlashed         HookType = 9
)

var HookType_name = map[int32]string{
	0: "AfterValidatorCreated",
	1: "BeforeValidatorModified",
	2: "AfterValidatorRemoved",
	3: "AfterValidatorBonded",
	4: "AfterValidatorBeginUnbonding",
	5: "BeforeDelegationCreated",
	6: "BeforeDelegationSharesModified",
	7: "BeforeDelegationRemoved",
	8: "AfterDelegationModified",
	9: "BeforeValidatorSlashed",
}

var HookType_value = map[string]int32{
	"AfterValidatorCreated":          0,
	"BeforeValidatorModified":        1,
	"AfterValidatorRemoved":          2,
	"AfterValidatorBonded":           3,
	"AfterValidatorBeginUnbonding":   4,
	"BeforeDelegationCreated":        5,
	"BeforeDelegationSharesModified": 6,
	"BeforeDelegationRemoved":        7,
	"AfterDelegationModified":        8,
	"BeforeValidatorSlashed":         9,
}

func (x HookType) String() string {
	return proto.EnumName(HookType_name, int32(x))
}

func (HookType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_94a1e4561f349256, []int{0}
}

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1e4561f349256, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// Message for adding, updating, or removing hook subscriptions for a contract
type MsgManageHookSubscription struct {
	ContractAddress string     `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Hooks           []HookType `protobuf:"varint,2,rep,packed,name=hooks,proto3,enum=v5.harpoon.HookType" json:"hooks,omitempty"`
}

func (m *MsgManageHookSubscription) Reset()         { *m = MsgManageHookSubscription{} }
func (m *MsgManageHookSubscription) String() string { return proto.CompactTextString(m) }
func (*MsgManageHookSubscription) ProtoMessage()    {}
func (*MsgManageHookSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1e4561f349256, []int{1}
}
func (m *MsgManageHookSubscription) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgManageHookSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgManageHookSubscription.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgManageHookSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgManageHookSubscription.Merge(m, src)
}
func (m *MsgManageHookSubscription) XXX_Size() int {
	return m.Size()
}
func (m *MsgManageHookSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgManageHookSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_MsgManageHookSubscription proto.InternalMessageInfo

func (m *MsgManageHookSubscription) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgManageHookSubscription) GetHooks() []HookType {
	if m != nil {
		return m.Hooks
	}
	return nil
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1e4561f349256, []int{2}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("v5.harpoon.HookType", HookType_name, HookType_value)
	proto.RegisterType((*MsgUpdateParams)(nil), "v5.harpoon.MsgUpdateParams")
	proto.RegisterType((*MsgManageHookSubscription)(nil), "v5.harpoon.MsgManageHookSubscription")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "v5.harpoon.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("neutron/harpoon/tx.proto", fileDescriptor_94a1e4561f349256) }

var fileDescriptor_94a1e4561f349256 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x41, 0x6f, 0xd3, 0x3e,
	0x14, 0xc0, 0x9b, 0xed, 0xbf, 0xfd, 0x57, 0x83, 0x58, 0xb0, 0x0a, 0x6b, 0xbb, 0x29, 0x8c, 0x72,
	0x29, 0x45, 0x6b, 0xb4, 0x42, 0x39, 0xec, 0x80, 0xb4, 0xc2, 0x01, 0x09, 0x55, 0x9a, 0x52, 0xc6,
	0x81, 0x03, 0x93, 0x5b, 0xbb, 0x4e, 0xb4, 0xc6, 0x2f, 0xb2, 0xdd, 0x6a, 0xbd, 0x21, 0x8e, 0x9c,
	0xf8, 0x18, 0x1c, 0x2b, 0x84, 0xf8, 0x0c, 0x3b, 0x4e, 0x9c, 0x38, 0x21, 0xd4, 0x1e, 0xfa, 0x35,
	0x50, 0x9a, 0xa4, 0xed, 0xb2, 0x8a, 0x4b, 0x62, 0xbf, 0x9f, 0xfd, 0xde, 0xef, 0xc5, 0x0e, 0xca,
	0x0b, 0xd6, 0xd7, 0x12, 0x84, 0xed, 0x12, 0x19, 0x00, 0x08, 0x5b, 0x5f, 0x54, 0x03, 0x09, 0x1a,
	0x30, 0x1a, 0xd4, 0xab, 0x71, 0xb0, 0x78, 0x97, 0xf8, 0x9e, 0x00, 0x7b, 0xf6, 0x8c, 0x70, 0x71,
	0xa7, 0x03, 0xca, 0x07, 0x65, 0xfb, 0x8a, 0xdb, 0x83, 0xc3, 0xf0, 0x15, 0x83, 0x42, 0x04, 0xce,
	0x66, 0x33, 0x3b, 0x9a, 0xc4, 0x28, 0xc7, 0x81, 0x43, 0x14, 0x0f, 0x47, 0x71, 0x74, 0x2f, 0xad,
	0x10, 0x10, 0x49, 0xfc, 0x78, 0x4f, 0xe9, 0x87, 0x81, 0xb6, 0x9b, 0x8a, 0x9f, 0x06, 0x94, 0x68,
	0x76, 0x32, 0x23, 0xf8, 0x39, 0xca, 0x92, 0xbe, 0x76, 0x41, 0x7a, 0x7a, 0x98, 0x37, 0xf6, 0x8d,
	0x72, 0xb6, 0x91, 0xff, 0xf9, 0xfd, 0x20, 0x17, 0x17, 0x3b, 0xa6, 0x54, 0x32, 0xa5, 0x5a, 0x5a,
	0x7a, 0x82, 0x3b, 0x8b, 0xa5, 0xb8, 0x8e, 0x36, 0xa3, 0xdc, 0xf9, 0xb5, 0x7d, 0xa3, 0x7c, 0xab,
	0x86, 0xab, 0x8b, 0x1e, 0xab, 0x51, 0xee, 0x46, 0xf6, 0xf2, 0xf7, 0x83, 0xcc, 0xd7, 0xe9, 0xa8,
	0x62, 0x38, 0xf1, 0xe2, 0xa3, 0x67, 0x9f, 0xa6, 0xa3, 0xca, 0x22, 0xcd, 0xe7, 0xe9, 0xa8, 0xf2,
	0x30, 0x71, 0xbe, 0x98, 0x5b, 0xa7, 0x24, 0x4b, 0xdf, 0x0c, 0x54, 0x68, 0x2a, 0xde, 0x24, 0x82,
	0x70, 0xf6, 0x1a, 0xe0, 0xbc, 0xd5, 0x6f, 0xab, 0x8e, 0xf4, 0x02, 0xed, 0x81, 0xc0, 0x8f, 0x91,
	0xd9, 0x01, 0xa1, 0x25, 0xe9, 0xe8, 0x33, 0x12, 0xf9, 0x46, 0x9d, 0x38, 0xdb, 0x49, 0x3c, 0x6e,
	0x03, 0x57, 0xd0, 0x86, 0x0b, 0x70, 0x1e, 0x4a, 0xaf, 0x97, 0xef, 0xd4, 0x72, 0xcb, 0xd2, 0x61,
	0xde, 0xb7, 0xc3, 0x80, 0x39, 0xd1, 0x92, 0xa3, 0x17, 0x37, 0x55, 0x9f, 0xac, 0x54, 0x5d, 0xad,
	0x55, 0x2a, 0xa0, 0x9d, 0x54, 0x1f, 0x0e, 0x53, 0x01, 0x08, 0xc5, 0x2a, 0xa3, 0x35, 0xb4, 0x95,
	0x94, 0xc3, 0x05, 0x74, 0xef, 0xb8, 0xab, 0x99, 0x7c, 0x47, 0x7a, 0x1e, 0x25, 0x1a, 0xe4, 0x4b,
	0xc9, 0x88, 0x66, 0xd4, 0xcc, 0xe0, 0x5d, 0xb4, 0xd3, 0x60, 0x5d, 0x90, 0x6c, 0xce, 0x9a, 0x40,
	0xbd, 0xae, 0xc7, 0xa8, 0x69, 0xdc, 0xdc, 0xe7, 0x30, 0x1f, 0x06, 0x8c, 0x9a, 0x6b, 0x38, 0x8f,
	0x72, 0xd7, 0x51, 0x03, 0x04, 0x65, 0xd4, 0x5c, 0xc7, 0xfb, 0x68, 0x2f, 0x45, 0x18, 0xf7, 0xc4,
	0xa9, 0x68, 0x83, 0xa0, 0x9e, 0xe0, 0xe6, 0x7f, 0x8b, 0x9a, 0xaf, 0x58, 0x8f, 0x71, 0x12, 0xb6,
	0x92, 0x08, 0x6d, 0xe0, 0x12, 0xb2, 0xd2, 0xb0, 0xe5, 0x12, 0xc9, 0xd4, 0xdc, 0x6b, 0x73, 0x55,
	0x82, 0xc4, 0xec, 0xff, 0x10, 0xce, 0xea, 0x2f, 0xd8, 0x7c, 0xe7, 0x16, 0x2e, 0xa2, 0xfb, 0xa9,
	0x76, 0x5b, 0x3d, 0xa2, 0x5c, 0x46, 0xcd, 0x6c, 0xed, 0x03, 0x5a, 0x6f, 0x2a, 0x8e, 0x4f, 0xd0,
	0xed, 0x6b, 0xd7, 0x77, 0x77, 0xf9, 0x04, 0x53, 0x9f, 0xbb, 0xf8, 0xe8, 0x1f, 0x30, 0x39, 0x8b,
	0xe2, 0xc6, 0xc7, 0xf0, 0x82, 0x36, 0xde, 0x5c, 0x8e, 0x2d, 0xe3, 0x6a, 0x6c, 0x19, 0x7f, 0xc6,
	0x96, 0xf1, 0x65, 0x62, 0x65, 0xae, 0x26, 0x56, 0xe6, 0xd7, 0xc4, 0xca, 0xbc, 0x3f, 0xe4, 0x9e,
	0x76, 0xfb, 0xed, 0x6a, 0x07, 0x7c, 0x3b, 0x3e, 0xff, 0x03, 0x90, 0x3c, 0x19, 0xdb, 0x83, 0xfa,
	0xd2, 0x75, 0xd0, 0xc3, 0x80, 0xa9, 0xf6, 0xe6, 0xec, 0x7f, 0x7b, 0xfa, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd5, 0x56, 0xf7, 0xd3, 0x12, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/v5.harpoon.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v5.harpoon.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v5.harpoon.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "neutron/harpoon/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgManageHookSubscription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgManageHookSubscription) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgManageHookSubscription) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hooks) > 0 {
		dAtA3 := make([]byte, len(m.Hooks)*10)
		var j2 int
		for _, num := range m.Hooks {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintTx(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgManageHookSubscription) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Hooks) > 0 {
		l = 0
		for _, e := range m.Hooks {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgManageHookSubscription) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgManageHookSubscription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgManageHookSubscription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v HookType
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= HookType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Hooks = append(m.Hooks, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Hooks) == 0 {
					m.Hooks = make([]HookType, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v HookType
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= HookType(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Hooks = append(m.Hooks, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Hooks", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
