// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: neutron/revenue/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines the parameters for the module.
type Params struct {
	// The asset used in revenue payments to validators. Expected to be a native token of the chain
	// with its denom metadata registered in the bank module. The denom metadata must have a defined
	// symbol field and contain a denom unit with an alias equal to the symbol and a specified
	// exponent.
	RewardAsset string `protobuf:"bytes,1,opt,name=reward_asset,json=rewardAsset,proto3" json:"reward_asset,omitempty"`
	// Quotation of the reward asset.
	RewardQuote *RewardQuote `protobuf:"bytes,2,opt,name=reward_quote,json=rewardQuote,proto3" json:"reward_quote,omitempty"`
	// Specifies performance requirements for validators in scope of blocks signing and creation. If
	// not met, the validator is not rewarded.
	BlocksPerformanceRequirement *PerformanceRequirement `protobuf:"bytes,3,opt,name=blocks_performance_requirement,json=blocksPerformanceRequirement,proto3" json:"blocks_performance_requirement,omitempty"`
	// Specifies performance requirements for validators in scope of the oracle price votes. If not
	// met, the validator is not rewarded.
	OracleVotesPerformanceRequirement *PerformanceRequirement `protobuf:"bytes,4,opt,name=oracle_votes_performance_requirement,json=oracleVotesPerformanceRequirement,proto3" json:"oracle_votes_performance_requirement,omitempty"`
	// Indicates the currently active type of payment schedule.
	PaymentScheduleType *PaymentScheduleType `protobuf:"bytes,5,opt,name=payment_schedule_type,json=paymentScheduleType,proto3" json:"payment_schedule_type,omitempty"`
	// The time window, in seconds, used to calculate the TWAP of the reward asset.
	TwapWindow int64 `protobuf:"varint,6,opt,name=twap_window,json=twapWindow,proto3" json:"twap_window,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRewardAsset() string {
	if m != nil {
		return m.RewardAsset
	}
	return ""
}

func (m *Params) GetRewardQuote() *RewardQuote {
	if m != nil {
		return m.RewardQuote
	}
	return nil
}

func (m *Params) GetBlocksPerformanceRequirement() *PerformanceRequirement {
	if m != nil {
		return m.BlocksPerformanceRequirement
	}
	return nil
}

func (m *Params) GetOracleVotesPerformanceRequirement() *PerformanceRequirement {
	if m != nil {
		return m.OracleVotesPerformanceRequirement
	}
	return nil
}

func (m *Params) GetPaymentScheduleType() *PaymentScheduleType {
	if m != nil {
		return m.PaymentScheduleType
	}
	return nil
}

func (m *Params) GetTwapWindow() int64 {
	if m != nil {
		return m.TwapWindow
	}
	return 0
}

// Defines information about the reward quote.
type RewardQuote struct {
	// The compensation amount measured in the quote asset. The amount is divided by the price of
	// the reward asset to determine the base revenue amount.
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The name of the quote asset. It is used as a quote in price queries to the slinky oracle
	// module to determine the price of the reward asset.
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
}

func (m *RewardQuote) Reset()         { *m = RewardQuote{} }
func (m *RewardQuote) String() string { return proto.CompactTextString(m) }
func (*RewardQuote) ProtoMessage()    {}
func (*RewardQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{1}
}
func (m *RewardQuote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardQuote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardQuote.Merge(m, src)
}
func (m *RewardQuote) XXX_Size() int {
	return m.Size()
}
func (m *RewardQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardQuote.DiscardUnknown(m)
}

var xxx_messageInfo_RewardQuote proto.InternalMessageInfo

func (m *RewardQuote) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RewardQuote) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

// A model that contains information specific to the currently active payment schedule type. The
// oneof implementations define the payment schedule that must be used currently.
// This is a module's parameter. It's not updated automatically in runtime in contrast to the
// payment schedule which is a state variable, but is updated via MsgUpdateParams.
type PaymentScheduleType struct {
	// Types that are valid to be assigned to PaymentScheduleType:
	//
	//	*PaymentScheduleType_MonthlyPaymentScheduleType
	//	*PaymentScheduleType_BlockBasedPaymentScheduleType
	//	*PaymentScheduleType_EmptyPaymentScheduleType
	PaymentScheduleType isPaymentScheduleType_PaymentScheduleType `protobuf_oneof:"payment_schedule_type"`
}

func (m *PaymentScheduleType) Reset()         { *m = PaymentScheduleType{} }
func (m *PaymentScheduleType) String() string { return proto.CompactTextString(m) }
func (*PaymentScheduleType) ProtoMessage()    {}
func (*PaymentScheduleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{2}
}
func (m *PaymentScheduleType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentScheduleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentScheduleType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentScheduleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentScheduleType.Merge(m, src)
}
func (m *PaymentScheduleType) XXX_Size() int {
	return m.Size()
}
func (m *PaymentScheduleType) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentScheduleType.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentScheduleType proto.InternalMessageInfo

type isPaymentScheduleType_PaymentScheduleType interface {
	isPaymentScheduleType_PaymentScheduleType()
	MarshalTo([]byte) (int, error)
	Size() int
}

type PaymentScheduleType_MonthlyPaymentScheduleType struct {
	MonthlyPaymentScheduleType *MonthlyPaymentScheduleType `protobuf:"bytes,4,opt,name=monthly_payment_schedule_type,json=monthlyPaymentScheduleType,proto3,oneof" json:"monthly_payment_schedule_type,omitempty"`
}
type PaymentScheduleType_BlockBasedPaymentScheduleType struct {
	BlockBasedPaymentScheduleType *BlockBasedPaymentScheduleType `protobuf:"bytes,5,opt,name=block_based_payment_schedule_type,json=blockBasedPaymentScheduleType,proto3,oneof" json:"block_based_payment_schedule_type,omitempty"`
}
type PaymentScheduleType_EmptyPaymentScheduleType struct {
	EmptyPaymentScheduleType *EmptyPaymentScheduleType `protobuf:"bytes,6,opt,name=empty_payment_schedule_type,json=emptyPaymentScheduleType,proto3,oneof" json:"empty_payment_schedule_type,omitempty"`
}

func (*PaymentScheduleType_MonthlyPaymentScheduleType) isPaymentScheduleType_PaymentScheduleType() {}
func (*PaymentScheduleType_BlockBasedPaymentScheduleType) isPaymentScheduleType_PaymentScheduleType() {
}
func (*PaymentScheduleType_EmptyPaymentScheduleType) isPaymentScheduleType_PaymentScheduleType() {}

func (m *PaymentScheduleType) GetPaymentScheduleType() isPaymentScheduleType_PaymentScheduleType {
	if m != nil {
		return m.PaymentScheduleType
	}
	return nil
}

func (m *PaymentScheduleType) GetMonthlyPaymentScheduleType() *MonthlyPaymentScheduleType {
	if x, ok := m.GetPaymentScheduleType().(*PaymentScheduleType_MonthlyPaymentScheduleType); ok {
		return x.MonthlyPaymentScheduleType
	}
	return nil
}

func (m *PaymentScheduleType) GetBlockBasedPaymentScheduleType() *BlockBasedPaymentScheduleType {
	if x, ok := m.GetPaymentScheduleType().(*PaymentScheduleType_BlockBasedPaymentScheduleType); ok {
		return x.BlockBasedPaymentScheduleType
	}
	return nil
}

func (m *PaymentScheduleType) GetEmptyPaymentScheduleType() *EmptyPaymentScheduleType {
	if x, ok := m.GetPaymentScheduleType().(*PaymentScheduleType_EmptyPaymentScheduleType); ok {
		return x.EmptyPaymentScheduleType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PaymentScheduleType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PaymentScheduleType_MonthlyPaymentScheduleType)(nil),
		(*PaymentScheduleType_BlockBasedPaymentScheduleType)(nil),
		(*PaymentScheduleType_EmptyPaymentScheduleType)(nil),
	}
}

// Monthly periods with payments made at the end of each month.
type MonthlyPaymentScheduleType struct {
}

func (m *MonthlyPaymentScheduleType) Reset()         { *m = MonthlyPaymentScheduleType{} }
func (m *MonthlyPaymentScheduleType) String() string { return proto.CompactTextString(m) }
func (*MonthlyPaymentScheduleType) ProtoMessage()    {}
func (*MonthlyPaymentScheduleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{3}
}
func (m *MonthlyPaymentScheduleType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonthlyPaymentScheduleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonthlyPaymentScheduleType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonthlyPaymentScheduleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonthlyPaymentScheduleType.Merge(m, src)
}
func (m *MonthlyPaymentScheduleType) XXX_Size() int {
	return m.Size()
}
func (m *MonthlyPaymentScheduleType) XXX_DiscardUnknown() {
	xxx_messageInfo_MonthlyPaymentScheduleType.DiscardUnknown(m)
}

var xxx_messageInfo_MonthlyPaymentScheduleType proto.InternalMessageInfo

// Periods defined by a specific number of blocks, with payments made when the required block
// count is reached.
type BlockBasedPaymentScheduleType struct {
	// The number of blocks in a payment period.
	BlocksPerPeriod uint64 `protobuf:"varint,1,opt,name=blocks_per_period,json=blocksPerPeriod,proto3" json:"blocks_per_period,omitempty"`
}

func (m *BlockBasedPaymentScheduleType) Reset()         { *m = BlockBasedPaymentScheduleType{} }
func (m *BlockBasedPaymentScheduleType) String() string { return proto.CompactTextString(m) }
func (*BlockBasedPaymentScheduleType) ProtoMessage()    {}
func (*BlockBasedPaymentScheduleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{4}
}
func (m *BlockBasedPaymentScheduleType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockBasedPaymentScheduleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockBasedPaymentScheduleType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockBasedPaymentScheduleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBasedPaymentScheduleType.Merge(m, src)
}
func (m *BlockBasedPaymentScheduleType) XXX_Size() int {
	return m.Size()
}
func (m *BlockBasedPaymentScheduleType) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBasedPaymentScheduleType.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBasedPaymentScheduleType proto.InternalMessageInfo

func (m *BlockBasedPaymentScheduleType) GetBlocksPerPeriod() uint64 {
	if m != nil {
		return m.BlocksPerPeriod
	}
	return 0
}

// Endless periods with payments never made.
type EmptyPaymentScheduleType struct {
}

func (m *EmptyPaymentScheduleType) Reset()         { *m = EmptyPaymentScheduleType{} }
func (m *EmptyPaymentScheduleType) String() string { return proto.CompactTextString(m) }
func (*EmptyPaymentScheduleType) ProtoMessage()    {}
func (*EmptyPaymentScheduleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{5}
}
func (m *EmptyPaymentScheduleType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyPaymentScheduleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyPaymentScheduleType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmptyPaymentScheduleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyPaymentScheduleType.Merge(m, src)
}
func (m *EmptyPaymentScheduleType) XXX_Size() int {
	return m.Size()
}
func (m *EmptyPaymentScheduleType) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyPaymentScheduleType.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyPaymentScheduleType proto.InternalMessageInfo

// Specifies a performance criteria that validators must meet to qualify for network rewards.
type PerformanceRequirement struct {
	// The fraction of the total performance a validator can miss without affecting their reward.
	// Represented as a decimal value in the range [0.0, 1.0], where 1.0 corresponds to 100%.
	AllowedToMiss cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=allowed_to_miss,json=allowedToMiss,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"allowed_to_miss"`
	// The minimum fraction of the total performance a validator must achieve to be eligible for
	// network rewards. Validators falling below this threshold will not receive any rewards.
	// Represented as a decimal value in the range [0.0, 1.0], where 1.0 corresponds to 100%.
	RequiredAtLeast cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=required_at_least,json=requiredAtLeast,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"required_at_least"`
}

func (m *PerformanceRequirement) Reset()         { *m = PerformanceRequirement{} }
func (m *PerformanceRequirement) String() string { return proto.CompactTextString(m) }
func (*PerformanceRequirement) ProtoMessage()    {}
func (*PerformanceRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e318e374514628b, []int{6}
}
func (m *PerformanceRequirement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PerformanceRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PerformanceRequirement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PerformanceRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerformanceRequirement.Merge(m, src)
}
func (m *PerformanceRequirement) XXX_Size() int {
	return m.Size()
}
func (m *PerformanceRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_PerformanceRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_PerformanceRequirement proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "neutron.revenue.Params")
	proto.RegisterType((*RewardQuote)(nil), "neutron.revenue.RewardQuote")
	proto.RegisterType((*PaymentScheduleType)(nil), "neutron.revenue.PaymentScheduleType")
	proto.RegisterType((*MonthlyPaymentScheduleType)(nil), "neutron.revenue.MonthlyPaymentScheduleType")
	proto.RegisterType((*BlockBasedPaymentScheduleType)(nil), "neutron.revenue.BlockBasedPaymentScheduleType")
	proto.RegisterType((*EmptyPaymentScheduleType)(nil), "neutron.revenue.EmptyPaymentScheduleType")
	proto.RegisterType((*PerformanceRequirement)(nil), "neutron.revenue.PerformanceRequirement")
}

func init() { proto.RegisterFile("neutron/revenue/params.proto", fileDescriptor_7e318e374514628b) }

var fileDescriptor_7e318e374514628b = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x4b, 0xdc, 0x40,
	0x14, 0x4f, 0x74, 0x5d, 0xe8, 0x6c, 0xcb, 0x62, 0xb4, 0x36, 0x5d, 0xd7, 0xac, 0x06, 0xc1, 0x3f,
	0xd5, 0x04, 0x5b, 0xe8, 0xa1, 0x3d, 0x14, 0x17, 0x0b, 0x82, 0x0a, 0x36, 0x95, 0xfe, 0x83, 0x32,
	0xcc, 0x26, 0xd3, 0xdd, 0x60, 0x92, 0x89, 0x99, 0x89, 0xeb, 0x7e, 0x8b, 0x1e, 0x3d, 0xf4, 0xe0,
	0x17, 0x28, 0x94, 0xd2, 0x0f, 0xe1, 0x51, 0x3c, 0x94, 0xd2, 0x83, 0x14, 0x3d, 0xf4, 0x6b, 0x94,
	0x99, 0xc9, 0x6a, 0xd9, 0xdd, 0x2c, 0xb4, 0x07, 0x65, 0xde, 0x7b, 0xbf, 0xf7, 0x7b, 0xbf, 0xcc,
	0x7b, 0xf3, 0x16, 0x54, 0x23, 0x9c, 0xb2, 0x84, 0x44, 0x76, 0x82, 0x0f, 0x71, 0x94, 0x62, 0x3b,
	0x46, 0x09, 0x0a, 0xa9, 0x15, 0x27, 0x84, 0x11, 0xad, 0x9c, 0x45, 0xad, 0x2c, 0x5a, 0x19, 0x47,
	0xa1, 0x1f, 0x11, 0x5b, 0xfc, 0x97, 0x98, 0xca, 0x7d, 0x97, 0xd0, 0x90, 0x50, 0x28, 0x2c, 0x5b,
	0x1a, 0x59, 0x68, 0xb2, 0x49, 0x9a, 0x44, 0xfa, 0xf9, 0x49, 0x7a, 0xcd, 0xef, 0xa3, 0xa0, 0xb8,
	0x2b, 0xaa, 0x68, 0x73, 0xe0, 0x76, 0x82, 0xdb, 0x28, 0xf1, 0x20, 0xa2, 0x14, 0x33, 0x5d, 0x9d,
	0x55, 0x17, 0x6f, 0x39, 0x25, 0xe9, 0x5b, 0xe7, 0x2e, 0xed, 0xd9, 0x35, 0xe4, 0x20, 0x25, 0x0c,
	0xeb, 0x23, 0xb3, 0xea, 0x62, 0xe9, 0x61, 0xd5, 0xea, 0x51, 0x66, 0x39, 0x02, 0xf4, 0x82, 0x63,
	0xba, 0x04, 0xc2, 0xd0, 0x42, 0x60, 0x34, 0x02, 0xe2, 0xee, 0x53, 0x18, 0xe3, 0xe4, 0x03, 0x49,
	0x42, 0x14, 0xb9, 0x18, 0x26, 0xf8, 0x20, 0xf5, 0x13, 0x1c, 0xe2, 0x88, 0xe9, 0xa3, 0x82, 0x72,
	0xa1, 0x8f, 0x72, 0xf7, 0x06, 0xef, 0xdc, 0xc0, 0x9d, 0xaa, 0xa4, 0x1b, 0x1c, 0xd5, 0x8e, 0xc0,
	0x3c, 0x49, 0x90, 0x1b, 0x60, 0x78, 0x48, 0x18, 0xce, 0x2f, 0x5a, 0xf8, 0xb7, 0xa2, 0x73, 0x92,
	0xf4, 0x15, 0xe7, 0xcc, 0xa9, 0xfc, 0x06, 0xdc, 0x8d, 0x51, 0x87, 0x1f, 0x21, 0x75, 0x5b, 0xd8,
	0x4b, 0x03, 0x0c, 0x59, 0x27, 0xc6, 0xfa, 0x98, 0x28, 0x35, 0xdf, 0x5f, 0x4a, 0xa2, 0x5f, 0x66,
	0xe0, 0xbd, 0x4e, 0x8c, 0x9d, 0x89, 0xb8, 0xdf, 0xa9, 0xd5, 0x40, 0x89, 0xb5, 0x51, 0x0c, 0xdb,
	0x7e, 0xe4, 0x91, 0xb6, 0x5e, 0x9c, 0x55, 0x17, 0x47, 0x1d, 0xc0, 0x5d, 0xaf, 0x85, 0xe7, 0x49,
	0xe1, 0xf8, 0xa4, 0xa6, 0x98, 0x4f, 0x41, 0xe9, 0xaf, 0x2e, 0x68, 0x53, 0xa0, 0x88, 0x42, 0x92,
	0x46, 0xb2, 0xad, 0x05, 0x27, 0xb3, 0xb4, 0x49, 0x30, 0x26, 0xbb, 0x3d, 0x22, 0xba, 0x2d, 0x0d,
	0xf3, 0x53, 0x01, 0x4c, 0x0c, 0x10, 0xa4, 0x9d, 0xa8, 0x60, 0x26, 0x24, 0x11, 0x6b, 0x05, 0x1d,
	0x38, 0xf8, 0xf3, 0xe4, 0x4d, 0x3e, 0xe8, 0xfb, 0xbc, 0x1d, 0x99, 0x35, 0x80, 0xb4, 0x6e, 0x7d,
	0xfd, 0xfd, 0x65, 0x79, 0xa9, 0x3b, 0xf2, 0x72, 0x18, 0xed, 0x7c, 0xfc, 0xa6, 0xe2, 0x54, 0xc2,
	0xdc, 0xa8, 0xf6, 0x59, 0x05, 0x73, 0x62, 0x26, 0x60, 0x03, 0x51, 0xec, 0xc1, 0x61, 0x5d, 0xb0,
	0xfa, 0x64, 0xd6, 0x79, 0x66, 0x9d, 0x27, 0x0e, 0x52, 0xba, 0xc6, 0x95, 0xae, 0xf4, 0x28, 0x1d,
	0x9a, 0xb2, 0xa9, 0x38, 0x33, 0x8d, 0x61, 0x00, 0xed, 0x58, 0x05, 0xd3, 0x38, 0x8c, 0x59, 0xde,
	0x85, 0x16, 0x85, 0xd2, 0xa5, 0x3e, 0xa5, 0xcf, 0x79, 0xce, 0x20, 0x91, 0x2b, 0x5c, 0xe4, 0x42,
	0x8f, 0xc8, 0x3c, 0xf4, 0xa6, 0xe2, 0xe8, 0x38, 0x8f, 0xe9, 0x5e, 0xce, 0x0c, 0x9b, 0x55, 0x50,
	0xc9, 0xef, 0x8f, 0xb9, 0x05, 0x66, 0x86, 0xde, 0x89, 0xb6, 0x0c, 0xc6, 0x6f, 0x96, 0x00, 0xff,
	0xf3, 0x89, 0x97, 0x8d, 0x65, 0xf9, 0xfa, 0x39, 0xef, 0x0a, 0xb7, 0x59, 0x01, 0x7a, 0x9e, 0x76,
	0xf3, 0x5c, 0x05, 0x53, 0x39, 0xcf, 0xef, 0x2d, 0x28, 0xa3, 0x20, 0x20, 0x6d, 0xec, 0x41, 0x46,
	0x60, 0xe8, 0x53, 0x2a, 0xd7, 0x59, 0x7d, 0xed, 0xf4, 0xa2, 0xa6, 0xfc, 0xbc, 0xa8, 0x4d, 0xcb,
	0xdd, 0x48, 0xbd, 0x7d, 0xcb, 0x27, 0x76, 0x88, 0x58, 0xcb, 0xda, 0xc6, 0x4d, 0xe4, 0x76, 0x36,
	0xb0, 0x7b, 0xfe, 0x6d, 0x15, 0x64, 0xab, 0x73, 0x03, 0xbb, 0xce, 0x9d, 0x8c, 0x69, 0x8f, 0xec,
	0xf8, 0x94, 0x6a, 0xef, 0xc1, 0x78, 0xb6, 0x3a, 0x3c, 0x88, 0x18, 0x0c, 0x30, 0xa2, 0xd9, 0xeb,
	0xf9, 0x1f, 0xf2, 0x72, 0x97, 0x6b, 0x9d, 0x6d, 0x73, 0xa6, 0xfa, 0xd6, 0xe9, 0xa5, 0xa1, 0x9e,
	0x5d, 0x1a, 0xea, 0xaf, 0x4b, 0x43, 0xfd, 0x78, 0x65, 0x28, 0x67, 0x57, 0x86, 0xf2, 0xe3, 0xca,
	0x50, 0xde, 0xad, 0x35, 0x7d, 0xd6, 0x4a, 0x1b, 0x96, 0x4b, 0x42, 0x3b, 0x9b, 0x86, 0x55, 0x92,
	0x34, 0xbb, 0x67, 0xfb, 0xf0, 0xb1, 0x7d, 0x74, 0xfd, 0xcb, 0xc1, 0xfb, 0x44, 0x1b, 0x45, 0xb1,
	0xe4, 0x1f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x3a, 0x0b, 0xf1, 0x59, 0x06, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TwapWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TwapWindow))
		i--
		dAtA[i] = 0x30
	}
	if m.PaymentScheduleType != nil {
		{
			size, err := m.PaymentScheduleType.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.OracleVotesPerformanceRequirement != nil {
		{
			size, err := m.OracleVotesPerformanceRequirement.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.BlocksPerformanceRequirement != nil {
		{
			size, err := m.BlocksPerformanceRequirement.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RewardQuote != nil {
		{
			size, err := m.RewardQuote.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RewardAsset) > 0 {
		i -= len(m.RewardAsset)
		copy(dAtA[i:], m.RewardAsset)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RewardAsset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RewardQuote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardQuote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardQuote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0x12
	}
	if m.Amount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PaymentScheduleType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaymentScheduleType != nil {
		{
			size := m.PaymentScheduleType.Size()
			i -= size
			if _, err := m.PaymentScheduleType.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *PaymentScheduleType_MonthlyPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentScheduleType_MonthlyPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MonthlyPaymentScheduleType != nil {
		{
			size, err := m.MonthlyPaymentScheduleType.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *PaymentScheduleType_BlockBasedPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentScheduleType_BlockBasedPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.BlockBasedPaymentScheduleType != nil {
		{
			size, err := m.BlockBasedPaymentScheduleType.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *PaymentScheduleType_EmptyPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentScheduleType_EmptyPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.EmptyPaymentScheduleType != nil {
		{
			size, err := m.EmptyPaymentScheduleType.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *MonthlyPaymentScheduleType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonthlyPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonthlyPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *BlockBasedPaymentScheduleType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockBasedPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockBasedPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksPerPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlocksPerPeriod))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EmptyPaymentScheduleType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyPaymentScheduleType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmptyPaymentScheduleType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PerformanceRequirement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PerformanceRequirement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PerformanceRequirement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RequiredAtLeast.Size()
		i -= size
		if _, err := m.RequiredAtLeast.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.AllowedToMiss.Size()
		i -= size
		if _, err := m.AllowedToMiss.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RewardAsset)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.RewardQuote != nil {
		l = m.RewardQuote.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.BlocksPerformanceRequirement != nil {
		l = m.BlocksPerformanceRequirement.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.OracleVotesPerformanceRequirement != nil {
		l = m.OracleVotesPerformanceRequirement.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.PaymentScheduleType != nil {
		l = m.PaymentScheduleType.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	if m.TwapWindow != 0 {
		n += 1 + sovParams(uint64(m.TwapWindow))
	}
	return n
}

func (m *RewardQuote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovParams(uint64(m.Amount))
	}
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *PaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentScheduleType != nil {
		n += m.PaymentScheduleType.Size()
	}
	return n
}

func (m *PaymentScheduleType_MonthlyPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MonthlyPaymentScheduleType != nil {
		l = m.MonthlyPaymentScheduleType.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}
func (m *PaymentScheduleType_BlockBasedPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockBasedPaymentScheduleType != nil {
		l = m.BlockBasedPaymentScheduleType.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}
func (m *PaymentScheduleType_EmptyPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EmptyPaymentScheduleType != nil {
		l = m.EmptyPaymentScheduleType.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}
func (m *MonthlyPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *BlockBasedPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlocksPerPeriod != 0 {
		n += 1 + sovParams(uint64(m.BlocksPerPeriod))
	}
	return n
}

func (m *EmptyPaymentScheduleType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PerformanceRequirement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AllowedToMiss.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.RequiredAtLeast.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardQuote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RewardQuote == nil {
				m.RewardQuote = &RewardQuote{}
			}
			if err := m.RewardQuote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerformanceRequirement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlocksPerformanceRequirement == nil {
				m.BlocksPerformanceRequirement = &PerformanceRequirement{}
			}
			if err := m.BlocksPerformanceRequirement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleVotesPerformanceRequirement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OracleVotesPerformanceRequirement == nil {
				m.OracleVotesPerformanceRequirement = &PerformanceRequirement{}
			}
			if err := m.OracleVotesPerformanceRequirement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentScheduleType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PaymentScheduleType == nil {
				m.PaymentScheduleType = &PaymentScheduleType{}
			}
			if err := m.PaymentScheduleType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapWindow", wireType)
			}
			m.TwapWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TwapWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardQuote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardQuote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardQuote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PaymentScheduleType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentScheduleType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentScheduleType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthlyPaymentScheduleType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MonthlyPaymentScheduleType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.PaymentScheduleType = &PaymentScheduleType_MonthlyPaymentScheduleType{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockBasedPaymentScheduleType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &BlockBasedPaymentScheduleType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.PaymentScheduleType = &PaymentScheduleType_BlockBasedPaymentScheduleType{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmptyPaymentScheduleType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EmptyPaymentScheduleType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.PaymentScheduleType = &PaymentScheduleType_EmptyPaymentScheduleType{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonthlyPaymentScheduleType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonthlyPaymentScheduleType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonthlyPaymentScheduleType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockBasedPaymentScheduleType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockBasedPaymentScheduleType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockBasedPaymentScheduleType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerPeriod", wireType)
			}
			m.BlocksPerPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyPaymentScheduleType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyPaymentScheduleType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyPaymentScheduleType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PerformanceRequirement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PerformanceRequirement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PerformanceRequirement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedToMiss", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AllowedToMiss.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredAtLeast", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequiredAtLeast.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
